Update npm-publish-github-packages.yml

diff --git a/.github/workflows/npm-publish-github-packages.yml b/.github/workflows/npm-publish-github-packages.yml
--- a/.github/workflows/npm-publish-github-packages.yml
+++ b/.github/workflows/npm-publish-github-packages.yml
@@ -35,20 +35,40 @@ jobs:
         with:
           node-version: 18
 
-      - name: Running Test
-        id: testng
+      - name: Run Tests with Retry
+        id: run_tests_with_retry
         shell: bash
         run: |
-          echo "STEP 1 ) Downloading sample suite"
-          git clone ${{ github.event.inputs.sampleRepoLink }}
-          echo "STEP 2) Download CLI and setting environment variables"
-          cd playwright_mobile_shopping
-          export LT_USERNAME=${{ github.event.inputs.username }}
-          export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
-          export LT_BUILD_NAME=${{ github.event.inputs.build }}
-          npm i 
-          npm install axios
-          echo $LT_BUILD_NAME
-          echo $LT_USERNAME
-          echo $LT_ACCESS_KEY
-          node playwright-${{ matrix.test }}
+          MAX_RETRIES=30
+          RETRY_COUNT=0
+          SUCCESS=false
+
+          while [ $RETRY_COUNT -le $MAX_RETRIES ]; do
+            echo "Attempt $((RETRY_COUNT+1))..."
+            echo "STEP 1) Downloading sample suite"
+            git clone ${{ github.event.inputs.sampleRepoLink }}
+            echo "STEP 2) Download CLI and setting environment variables"
+            cd playwright_mobile_shopping
+            export LT_USERNAME=${{ github.event.inputs.username }}
+            export LT_ACCESS_KEY=${{ github.event.inputs.accessKey }}
+            export LT_BUILD_NAME=${{ github.event.inputs.build }}
+            npm i 
+            npm install axios
+            echo $LT_BUILD_NAME
+            echo $LT_USERNAME
+            echo $LT_ACCESS_KEY
+            node playwright-${{ matrix.test }}
+            if [ $? -eq 0 ]; then
+              SUCCESS=true
+              break
+            else
+              RETRY_COUNT=$((RETRY_COUNT+1))
+              cd ..
+              rm -rf playwright_mobile_shopping
+            fi
+          done
+
+          if [ "$SUCCESS" = "false" ]; then
+            echo "All retries failed."
+            exit 1
+          fi
